#include "hal_data.h"
#include <stdio.h>
#include "drv/drv_systick.h"
#include "drv/drv_io.h"
#include "drv/drv_led.h"
#include "drv/drv_uart.h"
#include "drv/drv_key.h"
#include "drv/drv_dac.h"
#include "drv/drv_cmp.h"
#include "drv/drv_pwm.h"
#include "drv/drv_adc.h"
#include "drv/drv_adc_cb.h"
#include "drv/drv_hall.h"
#include "drv/drv_hall_cb.h"
#include "motor/m_foc.h"
#include "motor/m_ctrl.h"
#include "motor/m_parameter.h"
#include "motor/m_current_cal.h"
#include "arm_math.h"
#include "motor/m_rotor_angle.h"
#include "motor/m_observer.h"


FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

void vofa_plus_debug_func()
{
	char buf[256] = {0};
	#if 0	// δθ滤波效果调试
		sprintf(buf, "channels: %d,%d\r\n", \
		m_obs_angle_unit.q15_delta_angle_Tangle, m_obs_angle_unit.q15_delta_angle_Tangle_filtered);
		drv_uart_send_data((uint8_t *)buf, strlen(buf));
	#endif
	#if 0	// α轴电流估计调试
		sprintf(buf, "channels: %d,%d\r\n", \
		m_obs_unit.q15_i_alpha_n, m_obs_unit.q15_i_alpha_n_estimation);
		drv_uart_send_data((uint8_t *)buf, strlen(buf));
	#endif
	#if 0	// β轴电流估计调试
		sprintf(buf, "channels: %d,%d\r\n", \
		m_obs_unit.q15_i_beta_n, m_obs_unit.q15_i_beta_n_estimation);
		drv_uart_send_data((uint8_t *)buf, strlen(buf));
	#endif
	#if 1	// 测试速度计算滤波效果
		sprintf(buf, "channels: %d\r\n", m_obs_angle_unit.rpm);
		drv_uart_send_data((uint8_t *)buf, strlen(buf));
	#endif
	#if 0
		sprintf(buf, "channels: %d,%d,%d,%d,%d,%d,%d\r\n", \
		m_foc_unit.Us, \
		m_current_cal_unit.q15_iq, \
		m_current_cal_unit.q15_id, \
		m_current_cal_unit.q15_Uq, \
		m_current_cal_unit.q15_Ud, \
		m_foc_unit.q16_spd_target_value, \
		m_motor_ctrl.speed);
		drv_uart_send_data((uint8_t *)buf, strlen(buf));
	#endif
}


void hal_entry(void)
{
	drv_io_init();
	drv_led_init();
	drv_systick_init();   //systick 1ms
	drv_uart_init();
	drv_dac_init();
	drv_hall_init();
	drv_adc_init();
	drv_pwm_init();
	drv_cmp_init();
	drv_key_init();
	// 设置电机旋转方向
	m_motor_ctrl.direction = CCW;
	
	// 等待三相电流静态误差采集完成
	current_static_error_cal();
	printf("ia_static_error: %d\tib_static_error: %d\tic_static_error: %d\r\n", adc_unit.ia_static_error, adc_unit.ib_static_error, adc_unit.ic_static_error);
	
	
	m_obs_initial();	// 滑膜观测器初始化
	m_sensorless_angle_calculate_init(); // 无感角度计算低通滤波系数初始化
	
/* TODO: add your own code here */
	while(1)
	{
		m_calculate_Us();		// 开环阶段的Us模长计算
		motor_execute_ctrl();	// 轮询检测电位器的状态
		vofa_plus_debug_func();	// debug调试
	}
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
